### PR TITLE
fix: long manufacturer and model name not being displayed entirely, feat: webserver opening in Custom Tabs

### PR DESCRIPTION
**Pull request by geckoflume**
## Type of change

Type A:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] UI Feature
- [ ] Refactor/Code Cleanup

# Description (Type A)

Fixed manufacturer and model TextView not being displayed entirely if too long, made discovered_instance_list_item_layout responsive
Original                         |  &nbsp;&nbsp;&nbsp;New&nbsp;&nbsp;&nbsp;
:-------------------------:|:-------------------------:
Screenshot_2021-10-02-20-19-08-151_cloud valetudo companion | Screenshot_2021-10-02-20-18-16-122_cloud valetudo companion

Added webserver opening in Custom Tabs (if supported, see https://developer.chrome.com/docs/android/custom-tabs/)

### CODE REVIEW

**Review by TheLastProject — APPROVED** [review]
Each different change in a different commit. Clean and correct code. Tested and working well.

No complaints from me!

**Comment by Hypfer** [comment]
image
Why is the System ID so far away?

Also, why the custom tab thing? I'm pretty happy with it opening the real browser.
Having the custom tab just adds another step for the user to tap on "open in firefox" or similar, which does make sense if you're a commercial entity interested in keeping the user inside the app to bombard them with ads.

**Comment by geckoflume** [comment]
I thought it would look nicer to put the System ID in another column, but I can revert this:
Screenshot_2021-10-03-17-43-01-144_cloud valetudo companion

Regarding the Custom Tab thing, it is up to you! I thought the benefits of preloading the page + UI customizations (tab bar color/custom buttons) would be nice to have.

**Comment by Hypfer** [comment]
Bad bot

**Comment by Hypfer** [comment]
After having 30 open Valetudo tabs in my browser for a while now, I've reconsidered.
Thanks for pointing out that this custom tab thing exists!

I think I'll move the direct open in browser to the long press of the menu item.

**Pull request closed without merging**
